# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mopip77's Blog
email: mopip77@qq.com
logo: /logo.png
description: >- # this means to ignore newlines until "baseurl:"
  Sow nothing, reap nothing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.mopip77.tech" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: mopip77
# github_username:  mopip77
locale: zh-CN

permalink: /:year/:month/:title.html
author: mopip77

defaults:
  - scope: 
      path: "_posts"
    values:
      layout: "post"
      
# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-paginate

# theme settings
date_format: "%Y-%m-%d"

read_time: true
words_per_minute: 200

paginate: 8  # amount of posts to show per page
paginate_path: /page:num/

tag_archive_path: "/tags/#"

google_fonts:
  - name: "Noto Sans SC"
    weights: "400,400i,700,700i"
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

footer_links:
  - title: Github
    url: https://github.com/mopip77
    icon: fab fa-github-square
  - title: Mail
    url: "mailto: mopip77@qq.com"
    icon: fas fa-envelope
  - title: Weibo
    url: https://weibo.com/lwx1998
    icon: fab fa-weibo
  - title: Bilibili
    url: http://space.bilibili.com/2977639
    icon: fas fa-play-circle

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
